### ISSUE TITLE
Error with Rancher API

### ISSUE THREAD

**Issue by willseward** [disaster37/rancher-backup#13]
Cross post: rancher/rancher#8610

```text
4/27/2017 10:54:21 PM2017-04-28 03:54:21,972 - ERROR - Traceback (most recent call last):
4/27/2017 10:54:21 PM  File "/opt/backup/backup.py", line 229, in <module>
4/27/2017 10:54:21 PM    listStacks = rancherService.getStacks()
4/27/2017 10:54:21 PM  File "/opt/backup/fr/webcenter/backup/Rancher.py", line 83, in getStacks
4/27/2017 10:54:21 PM    stack['settings'] = self._client.action(stack, 'exportconfig')
4/27/2017 10:54:21 PM  File "/usr/lib/python2.7/site-packages/gdapi.py", line 401, in action
4/27/2017 10:54:21 PM    return self._post(url, data=self._to_dict(*args, **kw))
4/27/2017 10:54:21 PM  File "/usr/lib/python2.7/site-packages/gdapi.py", line 64, in wrapped
4/27/2017 10:54:21 PM    return fn(*args, **kw)
4/27/2017 10:54:21 PM  File "/usr/lib/python2.7/site-packages/gdapi.py", line 275, in _post
4/27/2017 10:54:21 PM    self._error(r.text)
4/27/2017 10:54:21 PM  File "/usr/lib/python2.7/site-packages/gdapi.py", line 255, in _error
4/27/2017 10:54:21 PM    raise ApiError(self._unmarshall(text))
4/27/2017 10:54:21 PMApiError: (ApiError(...), "Internal Server Error : Internal Server Error\n{'status': 500, 'code': u'Internal Server Error', 'links': {}, 'baseType': u'error', 'detail': None, 'actions': {}, 'message': u'Internal Server Error', 'type': u'error', 'id': u'9890d141-8956-4a3e-aef9-ce3f5a3895be'}")
4/27/2017 10:54:21 PM
```

**Comment by disaster37** [comment]
It's seems to be resolved by rancher team.
