### ISSUE TITLE
Unattented error occur : list index out of range

### ISSUE THREAD

**Issue by marcinwierzbicki** [disaster37/rancher-backup#23]
```
20.11.2017 10:51:052017-11-20 09:51:05,030 - INFO - Start to dump databases...
20.11.2017 10:51:052017-11-20 09:51:05,589 - ERROR - Unattented error occur : list index out of range
20.11.2017 10:51:052017-11-20 09:51:05,590 - ERROR - Traceback (most recent call last):
20.11.2017 10:51:05  File "/opt/backup/backup.py", line 222, in <module>
20.11.2017 10:51:05    listServices = rancherService.getServices()
20.11.2017 10:51:05  File "/opt/backup/fr/webcenter/backup/Rancher.py", line 60, in getServices
20.11.2017 10:51:05    instance['host'] = self._client._get(instance['links']['hosts'])[0]
20.11.2017 10:51:05IndexError: list index out of range
20.11.2017 10:51:05
20.11.2017 10:51:05[cont-init.d] 04-run-backup.sh: exited 1.
20.11.2017 10:51:05[cont-finish.d] executing container finish scripts...
20.11.2017 10:51:05[cont-finish.d] done.
20.11.2017 10:51:05[s6-finish] syncing disks.
```

Image: `webcenter/rancher-backup:2.0.1-1`

**Comment by marcinwierzbicki** [comment]
Data with `DEBUG=true`:
```
20.11.2017 11:19:402017-11-20 10:19:40,946 - DEBUG - http://192.168.254.254:8080 "GET /v2-beta/services/1s98/instances HTTP/1.1" 200 None
20.11.2017 11:19:402017-11-20 10:19:40,956 - DEBUG - http://192.168.254.254:8080 "GET /v2-beta/containers/1i176/hosts HTTP/1.1" 200 539
20.11.2017 11:19:402017-11-20 10:19:40,958 - ERROR - Unattented error occur : list index out of range
20.11.2017 11:19:402017-11-20 10:19:40,958 - ERROR - Traceback (most recent call last):
20.11.2017 11:19:40  File "/opt/backup/backup.py", line 222, in <module>
20.11.2017 11:19:40    listServices = rancherService.getServices()
20.11.2017 11:19:40  File "/opt/backup/fr/webcenter/backup/Rancher.py", line 60, in getServices
20.11.2017 11:19:40    instance['host'] = self._client._get(instance['links']['hosts'])[0]
20.11.2017 11:19:40IndexError: list index out of range
20.11.2017 11:19:40
20.11.2017 11:19:40[cont-init.d] 04-run-backup.sh: exited 1.
20.11.2017 11:19:40[cont-finish.d] executing container finish scripts...
20.11.2017 11:19:40[cont-finish.d] done.
```

`/v2-beta/containers/1i176/hosts`:
```
{
"type": "collection",
"resourceType": "host",
"links": {
"self": "…/v2-beta/containers/1i176/hosts"
},
"createTypes": { },
"actions": { },
"data": [ ],
"sortLinks": {
"accountId": "…/v2-beta/containers/1i176/hosts?sort=accountId",
"agentId": "…/v2-beta/containers/1i176/hosts?sort=agentId",
"agentState": "…/v2-beta/containers/1i176/hosts?sort=agentState",
"computeFree": "…/v2-beta/containers/1i176/hosts?sort=computeFree",
"computeTotal": "…/v2-beta/containers/1i176/hosts?sort=computeTotal",
"created": "…/v2-beta/containers/1i176/hosts?sort=created",
"description": "…/v2-beta/containers/1i176/hosts?sort=description",
"hostTemplateId": "…/v2-beta/containers/1i176/hosts?sort=hostTemplateId",
"id": "…/v2-beta/containers/1i176/hosts?sort=id",
"isPublic": "…/v2-beta/containers/1i176/hosts?sort=isPublic",
"kind": "…/v2-beta/containers/1i176/hosts?sort=kind",
"localStorageMb": "…/v2-beta/containers/1i176/hosts?sort=localStorageMb",
"memory": "…/v2-beta/containers/1i176/hosts?sort=memory",
"milliCpu": "…/v2-beta/containers/1i176/hosts?sort=milliCpu",
"name": "…/v2-beta/containers/1i176/hosts?sort=name",
"physicalHostId": "…/v2-beta/containers/1i176/hosts?sort=physicalHostId",
"removeAfter": "…/v2-beta/containers/1i176/hosts?sort=removeAfter",
"removeTime": "…/v2-beta/containers/1i176/hosts?sort=removeTime",
"removed": "…/v2-beta/containers/1i176/hosts?sort=removed",
"stackId": "…/v2-beta/containers/1i176/hosts?sort=stackId",
"state": "…/v2-beta/containers/1i176/hosts?sort=state",
"uri": "…/v2-beta/containers/1i176/hosts?sort=uri",
"uuid": "…/v2-beta/containers/1i176/hosts?sort=uuid"
},
"pagination": {
"first": null,
"previous": null,
"next": null,
"limit": 100,
"total": null,
"partial": false
},
"sort": null,
"filters": {
"accountId": null,
"agentId": null,
"agentState": null,
"computeFree": null,
"computeTotal": null,
"created": null,
"description": null,
"hostTemplateId": null,
"id": null,
"isPublic": null,
"kind": null,
"localStorageMb": null,
"memory": null,
"milliCpu": null,
"name": null,
"physicalHostId": null,
"removeAfter": null,
"removeTime": null,
"removed": null,
"stackId": null,
"state": null,
"uri": null,
"uuid": null
},
"createDefaults": { }
}
```

Rancher:  `v1.6.10`

**Comment by marcinwierzbicki** [comment]
This is our temporary solution (Monkey patch):
```
                if 'instances' in service['links']:
                    service['instances'] = self._client._get(service['links']['instances'])
                    for instance in service['instances']:
                        hosts = self._client._get(instance['links']['hosts'])
                        if isinstance(hosts, list):
                            instance['host'] = hosts[0]
                        else:
                            instance['host'] = hosts

                    logger.debug("Service %s have %d intances", service["name"], len(service['instances']))
```
I am not sure of this solution but it works.

**Comment by PierrickP** [comment]
I have the same error
`webcenter/rancher-backup:2.0.1-1``

Rancher: `1.6.10`

This line https://github.com/disaster37/rancher-backup/blob/3e589e6e8948309dbb9fce8423707a68db8e98cd/backup/src/fr/webcenter/backup/Rancher.py#L60

There are 2 instances, but the first has the `state: "purged"` and don't have data

**Comment by studna** [comment]
Same problem. @disaster37 Could be this fix released in stable version? I tried to use develop, but it did not work at all for me.
